[package]
name = "example"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["ordinary-http", "hook"]
ordinary-http = ["afast/ordinary-http"]
tls = ["afast/tls"]
hook = ["afast/hook"]

[dependencies]
afast = { path = "../afast", features = [
    "tcp",
    "http",
    "ws",
    "js",
    "ts",
    "kt",
    "rs",
    "doc",
    "marker",
    "rate-limit",
    "hook"
] }
afast-macros.workspace = true
afastdata.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
hyper.workspace = true
http-body-util.workspace = true

[[bin]]
name = "test_client"
path = "src/bin/test_client.rs"
